"""initial

Revision ID: 48e71098ed93
Revises: 0f3d933a9d39
Create Date: 2025-05-01 09:52:27.538706

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "48e71098ed93"
down_revision: Union[str, None] = "0f3d933a9d39"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_applications_id", table_name="applications")
    op.drop_index("ix_applications_title", table_name="applications")
    op.drop_table("applications")
    op.drop_table("image_upload")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "image_upload",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "filename", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
        sa.Column(
            "upload_date", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "size",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
            comment="File size in mb",
        ),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="image_upload_pkey"),
        sa.UniqueConstraint("filename", name="image_upload_filename_key"),
    )
    op.create_table(
        "applications",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("title", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("description", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="applications_pkey"),
    )
    op.create_index("ix_applications_title", "applications", ["title"], unique=False)
    op.create_index("ix_applications_id", "applications", ["id"], unique=False)
    # ### end Alembic commands ###
